import { CampusAdminInvitationsManagement } from "@/features/super-admin/components/campus-admins/campus-admin-invitations-management";
import { SuperAdminPageHeader } from "@/features/super-admin/components/super-admin-page-header";
import {
  getCampusAdminInvitations,
  getUniversities,
} from "@/features/super-admin/lib/super-admin-service";

export default async function SuperAdminCampusAdminsPage() {
  const [universities, invitations] = await Promise.all([
    getUniversities(),
    getCampusAdminInvitations(),
  ]);

  return (
    <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <SuperAdminPageHeader
        eyebrow="Campus admin management"
        title="Invite Campus Administrators"
        description="Campus Admins are created through university-specific invitations generated by a Super Admin."
      />
      <CampusAdminInvitationsManagement
        universities={universities}
        initialInvitations={invitations}
      />
    </main>
  );
}
