import Link from "next/link";

import { PageHero } from "@/components/public/page-hero";
import {
  Section,
  SectionHeading,
  SectionInner,
} from "@/components/public/section";
import { StatGrid } from "@/components/public/stat-grid";
import { Button } from "@/components/ui/button";
import { UniversityDiscovery } from "@/features/universities/components/university-discovery";
import { universities } from "@/features/universities/lib/mock-data";

export default function UniversitiesPage() {
  return (
    <>
      <PageHero
        eyebrow="University network"
        image="/images/photography/university-benefits.webp"
        primaryHref="/join"
        primaryLabel="Enrollment model"
        secondaryHref="/contact"
        secondaryLabel="Contact CampusHub"
        title="University access starts with verified invitations."
        description="Students no longer search for or self-select universities. CampusHub enrollment is invitation-based and automatically associates each student with the right university and college."
      />

      <Section>
        <SectionInner>
          <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
            <SectionHeading
              eyebrow="Public profiles"
              title="Explore institutions without using profiles as an enrollment path."
              description="University profiles remain public for trust and context. Actual student enrollment happens only through invitation links generated by authorized representatives."
            />
            <div className="flex flex-col gap-3 sm:flex-row">
              <Button asChild>
                <Link href="/join">How enrollment works</Link>
              </Button>
              <Button asChild variant="secondary">
                <Link href="/contact">Contact CampusHub</Link>
              </Button>
            </div>
          </div>
          <div className="mt-10">
            <UniversityDiscovery universities={universities} />
          </div>
        </SectionInner>
      </Section>

      <Section surface="surface">
        <SectionInner>
          <SectionHeading
            align="center"
            eyebrow="Discovery scale"
            title="A public entry point for multi-university growth."
            description="CampusHub discovery is designed to help students, staff, alumni, employers, and partners find the right institutional ecosystem."
          />
          <div className="mt-10">
            <StatGrid />
          </div>
        </SectionInner>
      </Section>
    </>
  );
}
