import type { RoleKey } from "@/features/authorization/roles";

export const PERMISSIONS = {
  PLATFORM_MANAGE: "platform:manage",
  UNIVERSITY_MANAGE: "university:manage",
  USER_READ: "user:read",
  USER_MANAGE: "user:manage",
  TENANT_READ: "tenant:read",
  TENANT_MANAGE: "tenant:manage"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<RoleKey, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.PLATFORM_MANAGE,
    PERMISSIONS.UNIVERSITY_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_MANAGE
  ],
  CAMPUS_ADMIN: [
    PERMISSIONS.UNIVERSITY_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_MANAGE
  ],
  REPRESENTATIVE: [PERMISSIONS.USER_READ, PERMISSIONS.TENANT_READ],
  COMMITTEE_MEMBER: [PERMISSIONS.USER_READ, PERMISSIONS.TENANT_READ],
  TEACHER: [PERMISSIONS.USER_READ, PERMISSIONS.TENANT_READ],
  STUDENT: [PERMISSIONS.TENANT_READ],
  ALUMNI: [PERMISSIONS.TENANT_READ],
  EMPLOYER: [PERMISSIONS.TENANT_READ]
};
