import type { IconType } from "react-icons";
import {
  FiActivity,
  FiAward,
  FiBarChart2,
  FiBell,
  FiBook,
  FiBookOpen,
  FiBriefcase,
  FiCalendar,
  FiCheckSquare,
  FiClipboard,
  FiDatabase,
  FiFlag,
  FiGift,
  FiGlobe,
  FiGrid,
  FiHeart,
  FiMap,
  FiMessageSquare,
  FiPackage,
  FiPieChart,
  FiSettings,
  FiShield,
  FiShoppingBag,
  FiStar,
  FiTool,
  FiTrendingUp,
  FiUsers,
} from "react-icons/fi";

import type { PlatformContentType } from "@/features/super-admin/lib/platform-content-service";

export type SuperAdminModule = {
  label: string;
  href: string;
  icon: IconType;
  eyebrow: string;
  title: string;
  description: string;
  contentType?: PlatformContentType;
};

export type SuperAdminNavSection = {
  label?: string;
  items: SuperAdminModule[];
};

export const superAdminNavSections: SuperAdminNavSection[] = [
  {
    label: "Overview",
    items: [
      {
        label: "Dashboard",
        href: "/super-admin/dashboard",
        icon: FiGrid,
        eyebrow: "Overview",
        title: "Dashboard",
        description: "Platform command center for CampusHub operations.",
      },
      {
        label: "Analytics",
        href: "/super-admin/analytics",
        icon: FiPieChart,
        eyebrow: "Platform analytics",
        title: "Analytics",
        description:
          "Cross-platform analytics for usage, growth, engagement, and operational health.",
      },
      {
        label: "Reports",
        href: "/super-admin/reports",
        icon: FiBarChart2,
        eyebrow: "Analytics",
        title: "Reports",
        description:
          "Platform-wide reporting for users, universities, marketplace activity, employability, and governance.",
      },
    ],
  },
  {
    label: "Institutions",
    items: [
      {
        label: "Universities",
        href: "/super-admin/universities",
        icon: FiBookOpen,
        eyebrow: "University management",
        title: "Universities",
        description:
          "Universities are the tenant foundation for CampusHub.",
      },
      {
        label: "Colleges",
        href: "/super-admin/colleges",
        icon: FiGlobe,
        eyebrow: "Institution structure",
        title: "Colleges",
        description:
          "Review colleges across every university and validate institutional structure.",
      },
      {
        label: "Departments",
        href: "/super-admin/departments",
        icon: FiDatabase,
        eyebrow: "Institution structure",
        title: "Departments",
        description:
          "Review departments across every college and university in the platform.",
      },
      {
        label: "Courses",
        href: "/super-admin/courses",
        icon: FiBook,
        eyebrow: "Institution structure",
        title: "Courses",
        description:
          "Manage department courses and official years of study across universities.",
      },
    ],
  },
  {
    label: "Identity",
    items: [
      {
        label: "Users",
        href: "/super-admin/users",
        icon: FiUsers,
        eyebrow: "Identity",
        title: "Users",
        description:
          "Global user management across students, teachers, administrators, alumni, employers, and leadership positions.",
      },
      {
        label: "Campus Admins",
        href: "/super-admin/campus-admins",
        icon: FiShield,
        eyebrow: "Campus admin management",
        title: "Campus Admins",
        description:
          "Campus Admins are created through university-specific invitations generated by a Super Admin.",
      },
      {
        label: "Students",
        href: "/super-admin/students",
        icon: FiUsers,
        eyebrow: "Identity",
        title: "Students",
        description:
          "Review student accounts across every university without relying on seeded data.",
      },
      {
        label: "Employers",
        href: "/super-admin/employers",
        icon: FiBriefcase,
        eyebrow: "Identity",
        title: "Employers",
        description:
          "Review employer accounts and organization access across CampusHub.",
      },
      {
        label: "Alumni",
        href: "/super-admin/alumni",
        icon: FiHeart,
        eyebrow: "Identity",
        title: "Alumni",
        description:
          "Review alumni profiles, network participation, and mentorship access.",
      },
    ],
  },
  {
    label: "Leadership",
    items: [
      {
        label: "Committees",
        href: "/super-admin/committees",
        icon: FiShield,
        eyebrow: "Leadership",
        title: "Committees",
        description:
          "View and manage committees across every university.",
        contentType: "committees",
      },
      {
        label: "Leadership Reports",
        href: "/super-admin/leadership-reports",
        icon: FiClipboard,
        eyebrow: "Leadership",
        title: "Leadership Reports",
        description:
          "Review reports submitted by student leadership and committee members.",
      },
      {
        label: "Polls",
        href: "/super-admin/polls",
        icon: FiPieChart,
        eyebrow: "Leadership",
        title: "Polls",
        description: "View and manage polls across every university.",
        contentType: "polls",
      },
      {
        label: "Suggestions",
        href: "/super-admin/suggestions",
        icon: FiMessageSquare,
        eyebrow: "Leadership",
        title: "Suggestions",
        description:
          "Review and manage suggestions submitted across the platform.",
        contentType: "suggestions",
      },
    ],
  },
  {
    label: "Engagement",
    items: [
      {
        label: "Events",
        href: "/super-admin/events",
        icon: FiCalendar,
        eyebrow: "Engagement",
        title: "Events",
        description: "View and manage events across every university.",
        contentType: "events",
      },
      {
        label: "Almanac",
        href: "/super-admin/almanac",
        icon: FiCalendar,
        eyebrow: "Engagement",
        title: "Almanac",
        description:
          "View and manage academic calendar and almanac records across universities.",
        contentType: "almanac",
      },
      {
        label: "Maps",
        href: "/super-admin/maps",
        icon: FiMap,
        eyebrow: "Engagement",
        title: "Maps",
        description:
          "View campus maps and saved location points across every university.",
        contentType: "map-locations",
      },
      {
        label: "Forums",
        href: "/super-admin/forums",
        icon: FiMessageSquare,
        eyebrow: "Engagement",
        title: "Forums",
        description: "View and manage forums across every university.",
        contentType: "forums",
      },
      {
        label: "Announcements",
        href: "/super-admin/announcements",
        icon: FiBell,
        eyebrow: "Engagement",
        title: "Announcements",
        description:
          "View and manage announcements across every university.",
        contentType: "announcements",
      },
    ],
  },
  {
    label: "Projects",
    items: [
      {
        label: "Projects",
        href: "/super-admin/projects",
        icon: FiStar,
        eyebrow: "Projects",
        title: "Projects",
        description:
          "Review student and alumni projects across the full CampusHub showcase.",
      },
      {
        label: "Project Analytics",
        href: "/super-admin/project-analytics",
        icon: FiTrendingUp,
        eyebrow: "Projects",
        title: "Project Analytics",
        description:
          "Measure project views, stars, saves, and engagement across universities.",
      },
    ],
  },
  {
    label: "Marketplace",
    items: [
      {
        label: "Marketplace",
        href: "/super-admin/marketplace",
        icon: FiShoppingBag,
        eyebrow: "Marketplace",
        title: "Marketplace",
        description:
          "Platform-wide marketplace operations across shops, products, services, and orders.",
      },
      {
        label: "Shops",
        href: "/super-admin/shops",
        icon: FiShoppingBag,
        eyebrow: "Marketplace",
        title: "Shops",
        description:
          "Review shops across every university marketplace.",
      },
      {
        label: "Products",
        href: "/super-admin/products",
        icon: FiPackage,
        eyebrow: "Marketplace",
        title: "Products",
        description:
          "Review marketplace products and services across every university.",
      },
      {
        label: "Marketplace Analytics",
        href: "/super-admin/marketplace-analytics",
        icon: FiBarChart2,
        eyebrow: "Marketplace",
        title: "Marketplace Analytics",
        description:
          "Measure marketplace reach, order requests, product activity, and shop performance.",
      },
    ],
  },
  {
    label: "Career",
    items: [
      {
        label: "Opportunities",
        href: "/super-admin/opportunities",
        icon: FiBriefcase,
        eyebrow: "Career",
        title: "Opportunities",
        description:
          "Review career opportunities and postings across every university.",
      },
      {
        label: "Applications",
        href: "/super-admin/employer-applications",
        icon: FiCheckSquare,
        eyebrow: "Career",
        title: "Applications",
        description:
          "Review opportunity applications and hiring pipeline activity.",
      },
      {
        label: "Mentorship",
        href: "/super-admin/mentorship",
        icon: FiHeart,
        eyebrow: "Career",
        title: "Mentorship",
        description:
          "Monitor mentorship profiles, requests, sessions, and outcomes across CampusHub.",
      },
      {
        label: "Career Analytics",
        href: "/super-admin/career-analytics",
        icon: FiBarChart2,
        eyebrow: "Career",
        title: "Career Analytics",
        description:
          "Measure employability, applications, mentorship, and hiring outcomes.",
      },
    ],
  },
  {
    label: "Gamification",
    items: [
      {
        label: "Badges",
        href: "/super-admin/badges",
        icon: FiAward,
        eyebrow: "Gamification",
        title: "Badges",
        description:
          "Manage badge definitions and earned badges across the platform.",
      },
      {
        label: "Achievements",
        href: "/super-admin/achievements",
        icon: FiGift,
        eyebrow: "Gamification",
        title: "Achievements",
        description:
          "Manage achievement definitions and user achievement progress.",
      },
      {
        label: "XP Leaderboards",
        href: "/super-admin/xp-leaderboards",
        icon: FiTrendingUp,
        eyebrow: "Gamification",
        title: "XP Leaderboards",
        description:
          "Review XP standings and leaderboard activity across universities.",
      },
    ],
  },
  {
    label: "Platform",
    items: [
      {
        label: "Audit Logs",
        href: "/super-admin/audit-logs",
        icon: FiActivity,
        eyebrow: "Platform controls",
        title: "Audit Logs",
        description:
          "Security and operational audit trail across CampusHub.",
      },
      {
        label: "Notifications",
        href: "/super-admin/notifications",
        icon: FiBell,
        eyebrow: "Platform controls",
        title: "Notifications",
        description:
          "Review platform notifications, delivery events, and notification intelligence.",
      },
      {
        label: "Integrations",
        href: "/super-admin/integrations",
        icon: FiTool,
        eyebrow: "Platform controls",
        title: "Integrations",
        description:
          "Manage external integration readiness and operational status.",
      },
      {
        label: "Feature Flags",
        href: "/super-admin/feature-flags",
        icon: FiFlag,
        eyebrow: "Platform controls",
        title: "Feature Flags",
        description:
          "Control rollout flags and feature availability across CampusHub.",
      },
      {
        label: "Settings",
        href: "/super-admin/settings",
        icon: FiSettings,
        eyebrow: "Account settings",
        title: "Settings",
        description:
          "Manage active account security and notification preferences.",
      },
      {
        label: "System Health",
        href: "/super-admin/system-health",
        icon: FiActivity,
        eyebrow: "Platform controls",
        title: "System Health",
        description:
          "Monitor platform readiness, backend integrations, and operational health.",
      },
    ],
  },
];

export const superAdminNavItems = superAdminNavSections.flatMap(
  (section) => section.items,
);

export function getSuperAdminModuleByHref(href: string) {
  return superAdminNavItems.find((item) => item.href === href);
}

export function getSuperAdminModuleBySlug(slug: string) {
  return getSuperAdminModuleByHref(`/super-admin/${slug}`);
}
